name: CD

on:
  workflow_dispatch:

permissions: read-all

jobs:
  publish_marketplace:
    name: Publish Action to Marketplace
    if: ${{ github.repository == 'sws2apps/firebase-deployment' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js current version
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Run Semantic Release to version and publish the action
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Push changes to remote repository
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -am "chore(actions): adding new dist folder for release"
          git push origin main
